### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Vanderscycle**
Corrected a small repetition in the README.md file.

For your review.

### CODE REVIEW

**Comment by Vanderscycle** [comment]
Hey sry for the double commit. I don't contribute enough to open-source projects and I thought that only my initial commit (readme update) would show.

I noticed in the TODO list that you wanted to add snippet support, and I've been using vsnip and friendly snip with great success. I know that this is your config so feel free to reject.

**Comment by siduck76** [comment]
@Vanderscycle Thanks for the readme correction and for the snippets plugin , I have no idea how they work .  In the PR , you havent added any configurationf for those plugins , would they work by default?

**Comment by Vanderscycle** [comment]
I haven't created a specific config file as the main functionality comes through lsp integration. A config file, as far as I've been toying with, would be mainly about changing the key mapping of the plugins that allows you to change placeholder names of the snips. 

I binded tab and shift-tab on my config for :bnext and :bprevious and so I haven't decided at the moment what keys to bind to the plugin in the future.

I can cancel this pr and resubmit another one with just the typo to allow you try the plugins.

**Comment by siduck76** [comment]
I have tried those snippet plugins and I dont get any lsp autocompletions , only vsnip :( 
 
 
image

**Comment by Vanderscycle** [comment]
I was a bit confused about your first message. friendly snips has a really good wiki reference and I cross referenced to make sure they were available as I was doublting myself. https://github.com/rafamadriz/friendly-snippets/wiki

I'll make a small change to the README.md tomorrow with the link to the friendy vsnip repo wiki. Also vsnip = {kind = "﬌"}, in compe/lua.lua makes vsnips much easier to spot. I'll make a one line change to it. w\With the pr tomorrow.

**Comment by siduck76** [comment]
can we add an icon with lspkind for vsnip completions? 
 
 
image

**Pull request merged**
